export enum MODAL_TYPE {
  CREATE_FOLDER = 'CREATE_FOLDER',
  EDIT_FOLDER = 'EDIT_FOLDER',
  CONFIRM_DELETE_FOLDER = 'CONFIRM_DELETE_FOLDER',
  CONFIRM_DELETE_STUDY_SET = 'CONFIRM_DELETE_STUDY_SET',
  REVIEW_COMPLETE = 'REVIEW_COMPLETE',
  REVIEW_QUIZ_COMPLETE = 'REVIEW_QUIZ_COMPLETE',
}
